import Foundation

final class PointCloudWriter {
    static let bytesPerPoint: Int64 = 15

    private let fileManager = FileManager.default
    private var handle: FileHandle?
    private(set) var workingURL: URL
    private(set) var pointCount: Int64 = 0

    init() throws {
        let directory = fileManager.temporaryDirectory
            .appendingPathComponent("LiDARScanner", isDirectory: true)
        try fileManager.createDirectory(at: directory, withIntermediateDirectories: true)

        workingURL = directory
            .appendingPathComponent(UUID().uuidString)
            .appendingPathExtension("pcbin")

        fileManager.createFile(atPath: workingURL.path, contents: nil)
        handle = try FileHandle(forWritingTo: workingURL)
    }

    deinit {
        try? handle?.close()
    }

    var rawByteCount: Int64 {
        pointCount * Self.bytesPerPoint
    }

    func append(_ points: [PointSample]) throws {
        guard !points.isEmpty, let handle else { return }

        var data = Data(capacity: points.count * Int(Self.bytesPerPoint))

        for point in points {
            appendFloat(point.position.x, to: &data)
            appendFloat(point.position.y, to: &data)
            appendFloat(point.position.z, to: &data)
            data.append(point.red)
            data.append(point.green)
            data.append(point.blue)
        }

        try handle.write(contentsOf: data)
        pointCount += Int64(points.count)
    }

    func finish() throws {
        try handle?.synchronize()
        try handle?.close()
        handle = nil
    }

    func exportPLY() throws -> URL {
        try finish()

        let scansDirectory = try scansDirectoryURL()
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd_HH-mm-ss"
        let filename = "LiDAR_Scan_\(formatter.string(from: Date())).ply"
        let outputURL = scansDirectory.appendingPathComponent(filename)

        fileManager.createFile(atPath: outputURL.path, contents: nil)
        let output = try FileHandle(forWritingTo: outputURL)
        defer { try? output.close() }

        let header = """
        ply
        format binary_little_endian 1.0
        comment Generated by LiDAR Scanner for iPhone and iPad
        element vertex \(pointCount)
        property float x
        property float y
        property float z
        property uchar red
        property uchar green
        property uchar blue
        end_header
        """ + "\n"

        try output.write(contentsOf: Data(header.utf8))

        let input = try FileHandle(forReadingFrom: workingURL)
        defer { try? input.close() }

        while true {
            let chunk = try input.read(upToCount: 1_048_576) ?? Data()
            if chunk.isEmpty { break }
            try output.write(contentsOf: chunk)
        }

        try output.synchronize()
        return outputURL
    }

    private func scansDirectoryURL() throws -> URL {
        let base = fileManager.urls(for: .documentDirectory, in: .userDomainMask).first
            ?? fileManager.temporaryDirectory
        let directory = base.appendingPathComponent("Scans", isDirectory: true)
        try fileManager.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory
    }

    private func appendFloat(_ value: Float, to data: inout Data) {
        var bits = value.bitPattern.littleEndian
        withUnsafeBytes(of: &bits) { raw in
            data.append(contentsOf: raw)
        }
    }
}
